Contact section
krisbobo/Portfolio-mobileVersionSkeleton pull request #3
Opened 2022-05-31 19:53 UTC by krisbobo

## Portfolio: Contact-form section ##
The following changes were introduced:
- A contact form section.
- A footer section.

2022-05-31 20:13 UTC, hiromataba requested changes
Hi @krisbobo and @OkoyeCharles     :wave: :wave: 

![almost-there](https://user-images.githubusercontent.com/75126481/160092588-b3f37e8e-a1d9-4b14-84fc-7ec1fed7b3e5.gif)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Your PR has a proper title and description  :+1: 
- Your linters are passing :heavy_check_mark:  
- Profesional README file :rocket: 

## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-31 20:13 UTC, hiromataba commented on index.html
> +        <li><input class="form-input" type="text" name="Name" placeholder="Text Input" maxlength="30" required></li>
- [ ] Please make the placeholder of this input: `Name` or first name and last name because now text input does not make a lot of sense for the person who will be checking form

2022-05-31 20:13 UTC, hiromataba commented on index.html
> +        <li class="button-container"><button class="form-button" type="submit">See Project</button></li>
- [ ] [OPTIONAL]Please make sure you clear your inputs after submitting

2022-05-31 20:13 UTC, hiromataba commented on README.md
> +
- [ ][OPTIONAL] I think it would be better to add more profiles to have a great network you may add, LinkedIn and twitter

2022-05-31 20:52 UTC, krisbobo commented on index.html
> +        <li class="button-container"><button class="form-button" type="submit">See Project</button></li>
Hi @hiromataba. Thanks for the review. I really don't understand what you mean by "clear your inputs after submitting". Can you please through more light on that?

2022-06-01 08:39 UTC, TedLivist approved these changes
## STATUS: APPROVED ✔️ ✔️

Hi @krisbobo,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-01 08:40 UTC, merged

2022-06-10 12:44 UTC, hiromataba commented on index.html
> +        <li class="button-container"><button class="form-button" type="submit">See Project</button></li>
Hello @krisbobo, 
I hope you are doing okay 
I meant that every time you submit the form your input should be reset to empty